# Copyright Contributors to the Pyro project.
#
# SPDX-License-Identifier: Apache-2.0

ignore:
  - "pyro/docutil.py"
  - "pyro/logger.py"

coverage:
  range: 60..95
  round: nearest
  precision: 2

comment: false
