name: pyro
channels:
  - conda-forge
  - soumith
dependencies:
  - Sphinx
  - cloudpickle>=0.3.1
  - flake8
  - funcy>=1.7.5
  - graphviz>=0.8
  - jupyter>=1.0.0
  - matplotlib>=1.3
  - networkx>=1.11
  - numpy>=1.7
  - pytest
  - pytorch
  - scipy>=0.19.0
  - torchvision
  - visdom>=0.1.4
  - pip:
    - sphinx_rtd_theme
